name: Django CI + Docker Build & Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ikavya23/lit-app:latest .

      # Step 5: Run migrations inside Docker container
      - name: Apply migrations
        run: |
          docker run --rm \
            -e DJANGO_SECRET_KEY=ci-secret \
            -w /app/inventory \
            ikavya23/lit-app:latest \
            python manage.py migrate

      # Step 6: Run Django tests
      - name: Run Django tests
        run: |
          docker run --rm \
            -e DJANGO_SECRET_KEY=ci-secret \
            -w /app/inventory \
            ikavya23/lit-app:latest \
            python manage.py test

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ikavya23/lit-app:latest
